title: UUNIVERSE
description: Android Developer

url: https://uuranus.github.io
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: Blog
      url: /blog
    - title: Contact
      url: /contact

social:
    github: uuranus
    email: uuranus.dev@gmail.com

google_analytics: "UA-58263416-1"

disqus:
    shortname: uuranus
